pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id "com.android.application" version "8.13.2"
        id "org.jetbrains.kotlin.android" version "2.3.10"
        id "org.jetbrains.kotlin.plugin.compose" version "2.3.10"
        id "io.github.takahirom.roborazzi" version "1.59.0"
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "example-app"
include ":app"
